%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: Z:\User\pc1aod\CODE\GEDbounds_clusterImprove\standardEEGlocs.csv
%
% Auto-generated by MATLAB on 31-Aug-2022 09:42:05

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3, "Encoding", "UTF-8");

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["label", "theta", "phi"];
opts.VariableTypes = ["string", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "label", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "label", "EmptyFieldRule", "auto");

% Import the data
standardEEGlocs = readtable(join(["standardEEGlocs.csv"],''), opts);


%% Clear temporary variables
clear opts